#!/bin/bash

echo '-----------------🚀Launching pre-commit hook-----------------'

MODIFIED_FILES=$(./gradlew ktlintFormat --daemon --dry-run | grep "modified:" | awk '{print $2}')
ADDED_FILES=$(./gradlew ktlintFormat --daemon --dry-run | grep "added:" | awk '{print $2}')
FILES_TO_COMMIT="$MODIFIED_FILES $ADDED_FILES"


./gradlew ktlintFormat --daemon

if [ $? -ne 0 ]; then
  echo '❌ ktlintFormat failed! Please fix the style errors.'
  exit 1
fi

echo '✅ ktlintFormat passed! Your code style is on point.'

if [[ -n "$FILES_TO_COMMIT" ]]; then
  echo "📝 Adding files to commit: $FILES_TO_COMMIT"
  git add $FILES_TO_COMMIT

  if [ $? -ne 0 ]; then
    echo '❌ Failed to add files to the commit.'
    exit 1
  fi
fi

exit 0
